[package]
name = "fbcon"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
rvos-rt = { path = "../rvos-rt" }
rvos = { path = "../../lib/rvos" }
rvos-proto = { path = "../../lib/rvos-proto" }

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
