[package]
name = "fbcon"
version = "0.1.0"
edition = "2021"

[dependencies]
rvos-rt.workspace = true
rvos.workspace = true
rvos-proto.workspace = true
rvos-gfx.workspace = true
termserv.workspace = true
